### ISSUE TITLE
Error in extract_CDS() function when using data from Ensembl

### ISSUE THREAD

**Issue by gabee-chan** [wu-lab-egio/EGIO#3]
Hi!

Your tool looks super useful and I'm really interested in using it. 

I've been able to run the example dataset where you provide all the files. Nonetheless, when I try to use Human and Mouse data from Ensembl I'm getting the error below:

`Traceback (most recent call last):
  File "/g/data/xc17/Gaby/ForEGIO/HumanMouse/__prepare_egio_extra.py", line 442, in <module>
    prepare_geio_extra(args.gtf, args.cdna, args.cds, args.species)
  File "/g/data/xc17/Gaby/ForEGIO/HumanMouse/__prepare_egio_extra.py", line 371, in prepare_geio_extra
    uftmp = uftmp + extract_CDS(ug,cdnaDt[iso],orfDt[iso],excoDt[iso],genechrDt[ug],genestrDt[ug])
  File "/g/data/xc17/Gaby/ForEGIO/HumanMouse/__prepare_egio_extra.py", line 38, in extract_CDS
    enidx = min(np.where(arr>=orfen)[0].tolist())
ValueError: min() arg is an empty sequence
BLAST options error: File /g/data/xc17/Gaby/ForEGIO/HumanMouse//extrainfo/hsa.exonfasta does not exist
Traceback (most recent call last):
  File "/g/data/xc17/Gaby/ForEGIO/HumanMouse/__prepare_egio_extra.py", line 442, in <module>
    prepare_geio_extra(args.gtf, args.cdna, args.cds, args.species)
  File "/g/data/xc17/Gaby/ForEGIO/HumanMouse/__prepare_egio_extra.py", line 371, in prepare_geio_extra
    uftmp = uftmp + extract_CDS(ug,cdnaDt[iso],orfDt[iso],excoDt[iso],genechrDt[ug],genestrDt[ug])
  File "/g/data/xc17/Gaby/ForEGIO/HumanMouse/__prepare_egio_extra.py", line 38, in extract_CDS
    enidx = min(np.where(arr>=orfen)[0].tolist())
ValueError: min() arg is an empty sequence
BLAST options error: File /g/data/xc17/Gaby/ForEGIO/HumanMouse//extrainfo/mm.exonfasta does not exist
Command line argument error: Argument "query". File is not accessible:  `/g/data/xc17/Gaby/ForEGIO/HumanMouse//extrainfo/hsa.exonfasta'
Command line argument error: Argument "query". File is not accessible:  `/g/data/xc17/Gaby/ForEGIO/HumanMouse//extrainfo/mm.exonfasta'
Traceback (most recent call last):
  File "/g/data/xc17/Gaby/ForEGIO/HumanMouse/__prepare_egio_blastn.py", line 205, in <module>
    summaryblastn(args.species1, args.blast1, args.exonanno1, args.species2, args.blast2, args.exonanno2, args.orthogen, args.coverage)
  File "/g/data/xc17/Gaby/ForEGIO/HumanMouse/__prepare_egio_blastn.py", line 20, in summaryblastn
    tf = open(str(exonanno1))
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/xc17/Gaby/ForEGIO/HumanMouse//extrainfo/hsa.exon'
rm: cannot remove '/g/data/xc17/Gaby/ForEGIO/HumanMouse//extrainfo/hsa.exonfasta': No such file or directory
rm: cannot remove '/g/data/xc17/Gaby/ForEGIO/HumanMouse//extrainfo/mm.exonfasta': No such file or directory
rm: cannot remove '/g/data/xc17/Gaby/ForEGIO/HumanMouse//extrainfo/hsa-mm': No such file or directory
rm: cannot remove '/g/data/xc17/Gaby/ForEGIO/HumanMouse//extrainfo/mm-hsa': No such file or directory
Traceback (most recent call last):
  File "/g/data/xc17/Gaby/ForEGIO/HumanMouse/__EGIO.py", line 1923, in <module>
    blastexon = pd.read_table(str(args.blastn),header=0,sep='\t')
  File "/g/data/xc17/Gaby/bin/anaconda3/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/g/data/xc17/Gaby/bin/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 779, in read_table
    return _read(filepath_or_buffer, kwds)
  File "/g/data/xc17/Gaby/bin/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 575, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/g/data/xc17/Gaby/bin/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 933, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/g/data/xc17/Gaby/bin/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1217, in _make_engine
    self.handles = get_handle(  # type: ignore[call-overload]
  File "/g/data/xc17/Gaby/bin/anaconda3/lib/python3.9/site-packages/pandas/io/common.py", line 789, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/xc17/Gaby/ForEGIO/HumanMouse//extrainfo/blastn_mapping_hsa-mm.tab'`

Here is the command I use to run EGIO:

`_RUN_egio.sh -s hsa -S mm -r $Human_path/Homo_sapiens.GRCh38.97.gtf -R $Mouse_path/Mus_musculus.GRCm39.104.gtf -e $Human_path/Homo_sapiens.GRCh38.cdna \
-E $Mouse_path/Mus_musculus.GRCm39.cdna -o $Human_path/Homo_sapiens.GRCh38.cds -O $Mouse_path/Mus_musculus.GRCm39.cds \
-h /g/data/xc17/Gaby/ForEGIO/HumMouse_orthogenes.txt -p 32 -i 0.8 -c 0.8 -m 2 -n -2 -g -1`

All my files (GTF, cDNA, CDS) are from [Ensembl](https://www.ensembl.org/)

Kind Regards,
Gaby Santos

**Comment by wu-lab-egio** [comment]
It seems that the script fails to generate hsa.exonfasta and mm.exonfasta. I will check the script and figure out whether there is something wrong in it. Please waiting for the response. Thanks.

**Comment by wu-lab-egio** [comment]
Hi, I have checked the scripts using your GTF, cDNA, CDS files, and the script works well. 

To run the script, you should redirect into the folder where EGIO scripts are located, this folder is default workdirection. It seems that you put EGIO scripts in "HumanMouse" folder. If yes, please change the work driection to "HumanMouse" folder : 
**cd path/to/HumanMouse**

I also see that the human and mouse files are in folders "Human_path" and "Mouse_path", please put these folders in the "HumanMouse" folder. "HumMouse_orthogenes.txt" can be put into "HumanMouse" folder, too. 

Run EGIO as follows: 
**_RUN_egio.sh -s hsa -S mm -r Human_path/Homo_sapiens.GRCh38.97.gtf -R Mouse_path/Mus_musculus.GRCm39.104.gtf -e Human_path/Homo_sapiens.GRCh38.cdna -E Mouse_path/Mus_musculus.GRCm39.cdna -o Human_path/Homo_sapiens.GRCh38.cds -O Mouse_path/Mus_musculus.GRCm39.cds -h HumMouse_orthogenes.txt -p 32 -i 0.8 -c 0.8 -m 2 -n -2 -g -1**

Any question, please let me know.

**Comment by gabee-chan** [comment]
Hi! Sorry for my late response. I'm still having issues running EGIO :(

I have EGIO scripts and files to run EGIO in the same directory (HumanMouse)
![image](https://user-images.githubusercontent.com/14879053/191700588-4aef6384-fe2d-405c-acff-08a92c0e61a2.png)

I ran EGIO with this command under the HumanMouse directory
` 
_RUN_egio.sh -s hsa -S mm -r Homo_sapiens.GRCh38.97.gtf -R Mus_musculus.GRCm39.104.gtf  -e Homo_sapiens.GRCh38.cdna.all.fa -E Mus_musculus.GRCm39.cdna.all.fa  -o Homo_sapiens.GRCh38.cds.all.fa -O Mus_musculus.GRCm39.cds.all.fa  -h HumMouse_orthogenes.txt -p 32 -i 0.8 -c 0.8 -m 2 -n -2 -g -1
`
But I'm getting a similar error as before:

species1 is hsa
species2 is mm
identity is 0.8
coverage is 0.8
match score is 2
mismatch penalty is -2
gap penalty is -1
use 32 core
prepare required files of egio
extract orf position based on cDNA and CDS sequence
207877 of mRNA sequence is read
120712 CDS sequence is read
extract transcript information
extract coding exon sequence from 60617 genes
Traceback (most recent call last):
  File "/g/data/xc17/Gaby/ForEGIO/HumanMouse/__prepare_egio_extra.py", line 442, in <module>
    prepare_geio_extra(args.gtf, args.cdna, args.cds, args.species)
  File "/g/data/xc17/Gaby/ForEGIO/HumanMouse/__prepare_egio_extra.py", line 371, in prepare_geio_extra
    uftmp = uftmp + extract_CDS(ug,cdnaDt[iso],orfDt[iso],excoDt[iso],genechrDt[ug],genestrDt[ug])
  File "/g/data/xc17/Gaby/ForEGIO/HumanMouse/__prepare_egio_extra.py", line 38, in extract_CDS
    enidx = min(np.where(arr>=orfen)[0].tolist())
ValueError: min() arg is an empty sequence


Building a new DB, current time: 09/22/2022 18:39:10
New DB name:   /g/data/xc17/Gaby/ForEGIO/HumanMouse/extrainfo/hsa/hsa
New DB title:  /g/data/xc17/Gaby/ForEGIO/HumanMouse//extrainfo/hsa.exonfasta
Sequence type: Nucleotide
Keep MBits: T
Maximum file size: 3000000000B
BLAST options error: File /g/data/xc17/Gaby/ForEGIO/HumanMouse//extrainfo/hsa.exonfasta does not exist
extract orf position based on cDNA and CDS sequence
117949 of mRNA sequence is read
67152 CDS sequence is read
extract transcript information
extract coding exon sequence from 55416 genes
Traceback (most recent call last):
  File "/g/data/xc17/Gaby/ForEGIO/HumanMouse/__prepare_egio_extra.py", line 442, in <module>
    prepare_geio_extra(args.gtf, args.cdna, args.cds, args.species)
  File "/g/data/xc17/Gaby/ForEGIO/HumanMouse/__prepare_egio_extra.py", line 371, in prepare_geio_extra
    uftmp = uftmp + extract_CDS(ug,cdnaDt[iso],orfDt[iso],excoDt[iso],genechrDt[ug],genestrDt[ug])
  File "/g/data/xc17/Gaby/ForEGIO/HumanMouse/__prepare_egio_extra.py", line 38, in extract_CDS
    enidx = min(np.where(arr>=orfen)[0].tolist())
ValueError: min() arg is an empty sequence


Building a new DB, current time: 09/22/2022 18:39:18
New DB name:   /g/data/xc17/Gaby/ForEGIO/HumanMouse/extrainfo/mm/mm
New DB title:  /g/data/xc17/Gaby/ForEGIO/HumanMouse//extrainfo/mm.exonfasta
Sequence type: Nucleotide
Keep MBits: T
Maximum file size: 3000000000B
BLAST options error: File /g/data/xc17/Gaby/ForEGIO/HumanMouse//extrainfo/mm.exonfasta does not exist
reciprocal blastn of hsa and mm: hsa as query
Command line argument error: Argument "query". File is not accessible:  `/g/data/xc17/Gaby/ForEGIO/HumanMouse//extrainfo/hsa.exonfasta'
reciprocal blastn of hsa and mm: mm as query
Command line argument error: Argument "query". File is not accessible:  `/g/data/xc17/Gaby/ForEGIO/HumanMouse//extrainfo/mm.exonfasta'
summarize reciprocal blastN



organize orthologous gene pairs
organize cds region information
Traceback (most recent call last):
  File "/g/data/xc17/Gaby/ForEGIO/HumanMouse/__prepare_egio_blastn.py", line 205, in <module>
    summaryblastn(args.species1, args.blast1, args.exonanno1, args.species2, args.blast2, args.exonanno2, args.orthogen, args.coverage)
  File "/g/data/xc17/Gaby/ForEGIO/HumanMouse/__prepare_egio_blastn.py", line 20, in summaryblastn
    tf = open(str(exonanno1))
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/xc17/Gaby/ForEGIO/HumanMouse//extrainfo/hsa.exon'
rm: cannot remove '/g/data/xc17/Gaby/ForEGIO/HumanMouse//extrainfo/hsa.exonfasta': No such file or directory
rm: cannot remove '/g/data/xc17/Gaby/ForEGIO/HumanMouse//extrainfo/mm.exonfasta': No such file or directory
rm: cannot remove '/g/data/xc17/Gaby/ForEGIO/HumanMouse//extrainfo/hsa-mm': No such file or directory
rm: cannot remove '/g/data/xc17/Gaby/ForEGIO/HumanMouse//extrainfo/mm-hsa': No such file or directory
detect orthologous exons and isoforms between species hsa and mm
Traceback (most recent call last):
  File "/g/data/xc17/Gaby/ForEGIO/HumanMouse/__EGIO.py", line 1923, in <module>
    blastexon = pd.read_table(str(args.blastn),header=0,sep='\t')
  File "/g/data/xc17/Gaby/bin/anaconda3/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/g/data/xc17/Gaby/bin/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 779, in read_table
    return _read(filepath_or_buffer, kwds)
  File "/g/data/xc17/Gaby/bin/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 575, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/g/data/xc17/Gaby/bin/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 933, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/g/data/xc17/Gaby/bin/anaconda3/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1217, in _make_engine
    self.handles = get_handle(  # type: ignore[call-overload]
  File "/g/data/xc17/Gaby/bin/anaconda3/lib/python3.9/site-packages/pandas/io/common.py", line 789, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/g/data/xc17/Gaby/ForEGIO/HumanMouse//extrainfo/blastn_mapping_hsa-mm.tab'

**Comment by wu-lab-egio** [comment]
Hi, I have checked the scripts again, and the script works well.

I notice that we might use different cDNA and CDS files of human, because they are of different data size as marked in the screenshot. What I use in the analysis is the release 97 at http://ftp.ensembl.org/pub/release-97/fasta/homo_sapiens/. Could you please send me the version of cDNA and CDS files of human that you use in the analysis? These files might help me to find the bugs.

Some transcripts even genes are added or deleted when a new version is released, these will cause inaccordance between gtf annotation and cDNA/CDS recordings, which might cause some errors to complete the whole analysis. I see that you use gtf files of release 97, and I suggest that you use the same version of cDNA and CDS files.

![Screen Shot 2022-09-22 at 22 08 20](https://user-images.githubusercontent.com/96556226/191769502-45b6db67-887a-4644-a275-e999f97f7d12.png)

**Comment by gabee-chan** [comment]
Hi sorry for my late reply, I tried again with the human 97 version and I'm getting the same error. 
When I run the example everything works smoothly so I guess something is wrong with a file...

I was wondering, if could you try running it with my list of orthologue genes, maybe that is what is causing the issue (not the right format or matching IDs?). I retrieve my list of orthologue genes using biomaRt package in R. Here is the file:
[HumMouse_orthogenes.txt](https://github.com/wu-lab-egio/EGIO/files/9712063/HumMouse_orthogenes.txt).

Thanks for your help!

**Comment by wu-lab-egio** [comment]
Hi,
I have updated the scripts, and you can try it again and see if it works.

By the way, I have run the scripts using your orthologous gene file, you can download the results at https://github.com/wu-lab-egio/mouse_vs_human/tree/main.

**Comment by gabee-chan** [comment]
Thank you so much!!! 

I ran it again and changed the mouse Ensembl data. I was using the 104 release and when I changed it to the 107 it worked!! I don't know what is the difference between the release version and if the main issue is the GTF or any of the fasta files. Maybe is something you guys might want to have a look at (?). Anyway, thanks so much for your prompt replies and help!
