### ISSUE TITLE
Questions about input file templates

### ISSUE THREAD

**Issue by Tang-pro** [wu-lab-egio/EGIO#5]
Hi, @wu-lab-egio 

Very useful software, but  this software is not generally friendly and convenient, here I encountered some errors
`/usr/bin/ld.gold: --push-state: unknown option
/usr/bin/ld.gold: use the --help option for usage information
collect2: error: ld returned 1 exit status
Traceback (most recent call last):

IndexError: list index out of range
BLAST options error: File extrainfo/Ghir.exonfasta does not exist
Command line argument error: Argument "query". File is not accessible:  `extrainfo/Gbar.exonfasta'
Command line argument error: Argument "query". File is not accessible:  `extrainfo/Ghir.exonfasta'`

Can you provide the template of the input file directly here?
Best !

**Comment by wu-lab-egio** [comment]
Hi,

I am sorry to miss the email. To find the input file format, please refer to the example files at  https://github.com/wu-lab-egio/EGIO_example_source. When running the sample, please unzip the xx.gtf.zip files first.

When preparing your input file, please make sure that the gtf and DNA fasta files are from the same genome annotation. Some genes may be kicked out or newly-predicted in the new annotation version, such as Ensembl release v102 vs release v99.
