### ISSUE TITLE
How to prepare orthologous genes in non-model species

### ISSUE THREAD

**Issue by Tang-pro** [wu-lab-egio/EGIO#6]
Hi, @wu-lab-egio 

There is no species I am studying in Inparanoid. I use OrthoFinder to identify orthologous genes. Here I need a protein sequence, but should I choose the protein sequence corresponding to the longest transcript? Or is there any other method?

Best!

**Comment by wu-lab-egio** [comment]
Hi,

According to previous studies, you can use protein sequence of the longest transcript as input.

**Comment by Tang-pro** [comment]
Hi, @wu-lab-egio 

But this seems a bit troublesome. First, extract the longest protein sequence to replace the gene, and then identify the orthologous isoform through orthologous gene. I would like to ask if there is any way to identify the orthologous gene directly from gene-level without using the protein sequence?

**Comment by wu-lab-egio** [comment]
Protein sequence is still required to generate orthologous gene pairs. For example, two genes might share similar sequence, but they might have great changes in peptide sequence by a single nucleaotide reading frame shift mutation.
